config/routes.rb
Rails.application.routes.draw do
  root 'services#index'
  resources :services
  resources :posts
  resources :employees
  resources :users
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employee = Employee.all
  end

  def show
    
      @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_url
    else
      render 'new'
    end

  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update(employee_params)
      redirect_to employees_url
    else
      render 'new'
    end
    
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_url, notice: "Your post was deleted"
  end


  private

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :title, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index

    @post = Post.all
  end

  def show
    
      @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_url
    else
      render 'new'
    end

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_url
    else
      render 'new'
    end
    
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url, notice: "Your post was deleted"
  end


  private

  def post_params
    params.require(:post).permit(:author, :content, :image, :title, :date, :preview)
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  def index

    @service = Service.all
  end

  def show
    
      @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to services_url
    else
      render 'new'
    end

  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])

    if @service.update(service_params)
      redirect_to services_url
    else
      render 'new'
    end
    
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to services_url, notice: "Your post was deleted"
  end


  private

  def service_params
    params.require(:service).permit(:name, :description, :image_url, :icon_name)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employees/_form.html.erb
  <div class="form">

    <%= form_for @employee do |f| %>

      <div class="field">
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </div>

      <div class="field">
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </div>

      <div class="field">
        <%= f.label :title%>
        <%= f.text_field :title %>
      </div>

      <div class="editable-content">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>


      <%= f.submit  %>

    <% end %>

    <script>
     $(function() {
          $('#edit').froalaEditor()
      });
      $(function() {
        $('#employee_description').froalaEditor({toolbarInline: false})
      });
    </script>
</div>

app/views/employees/edit.html.erb
<div class="container">

  <h2>Edit '<%= @employee.first_name %> <%= @employee.last_name %>'</h2>

  <%= render "form" %>
  
</div>

app/views/employees/index.html.erb
<div class="container">

<h2> List of all Leadership Employees </h2>
  <p> Click to edit </p>

  <% @employee.each do |employee| %>
    
    <div class="employee">

      <%= link_to "/employees/#{employee.id}" do %>

        <%= employee.first_name %> <%= employee.last_name %>

      <% end %>
    </div>


  <% end %>
</div>

app/views/employees/new.html.erb
<div class="container">

  <h2>Add new Leadership Employee</h2>

  <%= render "form" %>
  
</div>

app/views/employees/show.html.erb
  <div class="employee-title">

    <h2><%= @employee.first_name %> <%= @employee.last_name %></h2>
    <h3><%= @employee.title %></h3>

  </div>
<div class="container-medium">  
    <div class="fr-view">
      <%= raw sanitize(simple_format(@employee.description), :tags => %w(br p) ) %>
    </div>

    <div class="toolbar"> 
  <%= link_to edit_employee_path do %> <i class="fa fa-pencil-square-o"></i> <% end %> | <%= link_to  @employee, method: :delete, data: {confirm: "Are you sure you want to delete this?"} do %> <i class="fa fa-trash-o"></i> <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evolution Proxy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Oxygen|Montserrat' rel='stylesheet' type='text/css'>  
</head>
<body>
  
  <nav>
        
        <%= link_to services_url do  %>
          <%= image_tag 'logo.jpg' %>
        <% end %>
    

      <ul>
        <li><a href="https://evolutionproxy.herokuapp.com/services#leadership">Leadership</a></li>
        <li><a href="https://evolutionproxy.herokuapp.com/services#services">Integrated Services</a></li>
        <li><a href="/posts">News</a></li>
        <li><a href="https://evolutionproxy.herokuapp.com/services#contact">Contact</a></li>
      </ul>
  </nav>

<div class="content">

  <%= yield %>


  <footer>
    <div class="left">
      <%= image_tag 'logo.jpg'%>

      <p> Evolution Proxy is a sister-company of <a href="http://www.bayfieldstrategy.com/">Bayfield Strategy</a>, a leading financial communications firm.</p>

    </div>

    <ul class="right">
        <li><a href="https://evolutionproxy.herokuapp.com/services#leadership">Leadership</a></li>
        <li><a href="https://evolutionproxy.herokuapp.com/services#services">Integrated Services</a></li>
        <li><a href="/posts">News</a></li>
        <li><a href="https://evolutionproxy.herokuapp.com/services#contact">Contact</a></li>
       <i class="fa fa-twitter"></i>
       <i class="fa fa-linkedin"></i>
    </ul>

   



  </footer>
</div>

</body>
</html>

app/views/posts/_form.html.erb
  <div class="form">

    <%= form_for @post do |f| %>

        <div class="field-long">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>

        <div class="field">
          <%= f.label :image %>
          <%= f.text_field :image %>
        </div>

        <div class="field">
          <%= f.label :author %>
          <%= f.text_field :author %>
        </div>

         <div class="field">
          <%= f.label :date %>
          <%= f.date_field :date %>
        </div>

        <div class="field-long">
        <%= f.label :preview %>
        <%= f.text_area :preview %>
      </div>

      <div class="editable-content">
        <%= f.label :content %>
        <%= f.text_area :content %>
      </div>


      <%= f.submit  %>

    <% end %>

    <script>
     $(function() {
          $('#edit').froalaEditor()
      });
      $(function() {
        $('#post_content').froalaEditor({toolbarInline: false})
      });
   
    </script>
</div>

app/views/posts/edit.html.erb
<div class="container">

<h2> Edit <%= @post.title %> </h2>

<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<div class="container-medium-post">

  <h1> News </h1>


  
  <% @post.each do |post| %>
    
    <div class="post">

      <%= link_to "/posts/#{post.id}" do %>

        
        <div class="post-image-container">
          <%= image_tag(post.image) %>
        </div>

        <div class="post-info-container">
          <h3><%= post.title %> </h3>
          <p><%= post.author %><p>
            <%= post.preview %>
        </div>

      

      <% end %>
    </div>


  <% end %>

  <div class="toolbar">
    <%= link_to "+ Add a new post", new_post_url %> | Click on any post to edit
  </div>

</div>

app/views/posts/new.html.erb
<div class="container">

<h2> Add new post </h2>

<%= render 'form' %>

</div>

app/views/posts/show.html.erb
  <div class="post-title" style ="background: url('<%=@post.image %>') no-repeat center center fixed;">
    <div class="picture-gradient"></div>
      <div class="container-medium">
        <h2><%= @post.title %></h2>
        <p><strong>By <%= @post.author %> </strong></p>
      </div>
  
</div>

<div class="container-medium">
  
    <h4><%= @post.date %></h4>
  
  <div class="fr-view">
    <%= @post.content.html_safe %>
  </div>

   <div class="toolbar"> 
  <%= link_to edit_post_path do %> <i class="fa fa-pencil-square-o"></i> <% end %> | <%= link_to  @post, method: :delete, data: {confirm: "Are you sure you want to delete this?"} do %> <i class="fa fa-trash-o"></i> <% end %>
  </div>
</div>

app/views/services/_form.html.erb
  <div class="form">

    <%= form_for @service do |f| %>

      <div class="field-long">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :image_url %>
        <%= f.text_field :image_url %>
      </div>

      <div class="field">
        <%= f.label :icon_name %>
        <%= f.text_field :icon_name %>
      </div>

      <div class="editable-content">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>


      <%= f.submit  %>

    <% end %>

    <script>
     $(function() {
          $('#edit').froalaEditor()
      });
      $(function() {
        $('#service_description').froalaEditor({toolbarInline: false})
      });
    </script>
</div>

app/views/services/edit.html.erb
<div class="container">

  <h3> Edit '<%= @service.name %>' </h3>
  <%= link_to "x Delete", @service, method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>
  

  <%= render "form" %>

</div>

app/views/services/index.html.erb
<div class="landing">
<div class="picture-gradient light"></div>
  <h1> A New Generation of Shareholder Solicitation Experts in Canada </h1>
</div>

<div class="two-pane-explainer">

  <div class="short">

    <div class="title">
      <hr/>
      <h2> What we do </h2>
      <hr/>
    </div>

  </div>

  <div class="long">

    <p> 
    Evolution Proxy specializes in delivering victories to our clients through an integrated and highly calibrated approach. Evolution Proxy combines the very best in proxy solicitation expertise, powerful communications techniques, corporate governance advice and the strategic experience that comes with over 100 career engagements. 
    </p>

  </div>
</div>

        



<div class="leadership" id="leadership">

<div class="two-pane-explainer">
  
  <div class="short lead"><div class="title">
    <hr/> 
    <h2> Leadership </h2>
    <hr/>
  </div>
</div>

  <div class="long lead">
    <p> Evolution Proxy’s new generation of shareholder solicitation experts will combine their experience on over 100 career engagements and market knowledge to develop an integrated, strategic approach to your unique situation. </p>
  </div>

</div>

  <div class="container">

      <h2> Evolution Proxy’s Leadership Team: </h2>

      <%= link_to'/employees/1' do %>
          <div class="profile left">
            <h3> Riyaz Lalani</h3>
            <h4>President</h4>
            <h4>rlalani@evolutionproxy.com</h4>
            <p>Riyaz specializes in financial transactions, shareholder actions, crisis communications and media relations. Our clients benefit from his extensive experience working on over 85 engagements in Canada, the United States, the UK and Europe, with public companies, boards of directors, shareholders and the media.</p>
          </div>
      <% end %>

      <%= link_to'/employees/4' do %>
      <div class="profile right">
        <h3>Chang Park </h3>
        <h4>Chief Operating Officer</h4>
        <h4>cpark@evolutionproxy.com</h4>
        <p>Chang has extensive experience in managing solicitation campaigns related to proxy contests, annual and special meetings, and M&A transactions. He has been involved in over 50 proxy contests and dozens of M&A transactions, both in Canada and the United States.</p>
      </div>
      <% end %>
  </div>
</div>

<div class="services" id="services">
 <div class="picture-gradient"></div>
  <div class="container-thin">

    <h2>Integrated Services</h2>

    <p> No matter what side of the campaign we are on, Evolution Proxy combines the very best in proxy solicitation knowledge, powerful communications techniques, corporate governance advice and the strategic experience that comes with over 100 career engagements to deliver a winning strategy. </p>

    <% @service.each do |service| %>
      <%= link_to "/services/#{service.id}" do%>
        <div class="service">
          <div class="service-icon"> <i class="<%= service.icon_name %>"></i> </div>
          <h3>  <%= service.name %>  </h3>
        </div>
      <% end %>
    <% end %>

  </div>
</div>


<div class="two-pane-explainer" id="contact">

      <div class="short">
        <div class="title">
          <h2>Get in touch</h2>
        </div>
      </div>

  <div class="long">
    <p class="right"><a href="mailto:info@evolutionproxy.com">Send us an email</a> <br/>
    Phone: 416-907-9365 <br/>
  </p>

  <p class="left"> 
    357 Bay Street, Suite 502<br/>
    Toronto, ON<br/>
    M5H 2T7 <br/>
  </p>
</div>

app/views/services/new.html.erb
<div class="container">

  <h2> Add a new service </h2>

  <%= render "form" %>

</div>

app/views/services/show.html.erb
<div class="title-service" style="
background: url('<%= @service.image_url %>') no-repeat bottom center fixed;
-webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  width: 100%;
  position: relative;">

  <div class="picture-gradient"></div>

  <h2> <%= @service.name %> </h2>
</div>

<div class="container-thin">
  <div class="fr-view">
    <%= @service.description.html_safe   %>
  </div>

 <div class="toolbar"> 
  <%= link_to edit_service_path do %> <i class="fa fa-pencil-square-o"></i> <% end %> | <%= link_to  @service, method: :delete, data: {confirm: "Are you sure you want to delete this?"} do %> <i class="fa fa-trash-o"></i> <% end %>
  </div>
</div>  